#ifndef render_fonts_h
#define render_fonts_h
#include <stdint.h>

/*
  Define ENABLE_PARAMETER_GATHER to help determine the extra fields added to the
  GFXfont structure yAbove and yBelow that are not generated by fontconverter.
  Call display_fontParameter() for each font you need to know the values for.
*/
//#define ENABLE_PARAMETER_GATHER	1


/*****************************************************************************
    Constants
 *****************************************************************************/

typedef enum {
	FMOverlay,		// Overlay with only foreground colour
	FMOverwrite,	// Overwrite with both foreground and background colours
	FMOutine		  //Overlay with foreground and colour and outline with background colour
} TFontMode;



typedef enum {
	XALeft,   // Place the text at the left edge of the rectangle
	XACentre,	// Place the text at the center of the rectangle
	XARight  	// Place the text at the right edge of the rectangle
} TXAlign;



typedef enum {
	YATop,    // Place the text at the top edge of the rectangle
	YACentre,	// Place the text at the center of the rectangle
	YABottom 	// Place the text at the Bottom edge of the rectangle
} TYAlign;



/*****************************************************************************
    Types
 *****************************************************************************/

// Font structures for newer Adafruit_GFX (1.1 and later).
// Example fonts are included in 'Fonts' directory.
// To use a font in your Arduino sketch, #include the corresponding .h
// file and pass address of GFXfont struct to setFont().  Pass NULL to
// revert to 'classic' fixed-space bitmap font.

typedef struct GFXglyph { // Data stored PER GLYPH
	uint16_t bitmapOffset;     // Pointer into GFXfont->bitmap
	uint8_t  width, height;    // Bitmap dimensions in pixels
	uint8_t  xAdvance;         // Distance to advance cursor (x axis)
	int8_t   xOffset, yOffset; // Dist from cursor pos to UL corner
} GFXglyph;



typedef struct GFXfont { // Data stored for FONT AS A WHOLE:
	uint8_t  *bitmap;      // Glyph bitmaps, concatenated
	GFXglyph *glyph;       // Glyph array
	uint8_t   first, last; // ASCII extents
	uint8_t   yAdvance;    // Newline distance (y axis)
// == The following two fields are an extension of the Adafruit struct ===
// You can use display_fontParameter() do find the actual values is converting
// an original Adafruit GFXfont record
	uint8_t	  yAbove;      // Maximum amount above base line characters reach
                         // It is the maximum value of any glyph->yOffset[] made positive
	uint8_t	  yBelow;      // Maximum amount below base line characters reach
	   	   	   	   	   	   // It is the maximum value of any glyph->yOffset[n]+glyph->height
} GFXfont;
#endif